// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALPgXdZLUmzZ8_DixKUDdgZpHKsVQVei0',
    appId: '1:343513836516:web:e995192049e5df2bc0b5f1',
    messagingSenderId: '343513836516',
    projectId: 'revamph-39a1b',
    authDomain: 'revamph-39a1b.firebaseapp.com',
    storageBucket: 'revamph-39a1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIE_rj54MRDBWKAUqOwduM6U5C2TAkxqA',
    appId: '1:343513836516:android:3c87e79d45c58ca4c0b5f1',
    messagingSenderId: '343513836516',
    projectId: 'revamph-39a1b',
    storageBucket: 'revamph-39a1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYOqjtUtstDv2BK5fCo00g6yGnlwtAjE',
    appId: '1:343513836516:ios:b71110f7cd563c8ac0b5f1',
    messagingSenderId: '343513836516',
    projectId: 'revamph-39a1b',
    storageBucket: 'revamph-39a1b.appspot.com',
    iosClientId: '343513836516-eouchoe5i2hveim6dj5u1aj6ivaf88mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.revamph',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqYOqjtUtstDv2BK5fCo00g6yGnlwtAjE',
    appId: '1:343513836516:ios:b71110f7cd563c8ac0b5f1',
    messagingSenderId: '343513836516',
    projectId: 'revamph-39a1b',
    storageBucket: 'revamph-39a1b.appspot.com',
    iosClientId: '343513836516-eouchoe5i2hveim6dj5u1aj6ivaf88mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.revamph',
  );
}
